refactor: modernize
MapColonies/js-logger pull request #16
Opened 2024-09-19 13:13 UTC by CptSchnitz

2024-09-23 10:54 UTC, netanelC requested changes

2024-09-23 10:54 UTC, netanelC commented on .github/dependabot.yml
> +      - dependency-name: "@map-colonies/schemas"
Unnecessary

2024-09-23 11:15 UTC, CptSchnitz commented on .github/dependabot.yml
> +      - dependency-name: "@map-colonies/schemas"
removed

2024-09-24 06:05 UTC, netanelC approved these changes

2024-09-24 10:21 UTC, merged